# Generated by Django 6.0.1 on 2026-01-28 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeroSlide',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('subtitle', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('buttonText', models.CharField(max_length=255)),
                ('buttonLink', models.CharField(max_length=500)),
                ('image', models.CharField(max_length=1000)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
