# Generated by Django 6.0.1 on 2026-04-22 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_user_is_email_verified_emailverificationotp'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='mobile_image',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='heroslide',
            name='mobile_image',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
